---
title: "Produzindo Gráficos"
output: html_notebook
---
'''
Histograma
'''{r}

trees
hist(trees$Height)
hist(trees$Height, main="Árvores", ylab="Frequência", xlab="Altura", col="blue")
hist(trees$Height, main="Árvores", ylab="Frequência", xlab="Altura", col="blue",
     density=20, breaks=20)

'''
Densidade
'''{r}

densidade = density(trees$Height)
plot(densidade)

'''
Densidade sobre o histograma.
'''{r}

hist(trees$Height, main=NULL, xlab=NULL, ylab=NULL)
par(new=TRUE)
plot(densidade)

'''
Dispersão: Um gráfico de dispersão é muito importante quando buscamos
analisar variáveis continuas.
'''{r}

plot(trees$Girth, trees$Volume)

plot(trees$Girth, trees$Volume, main="Árvores")

plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab="Volume", col="blue",
    main="Árvores")
    
plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab="Volume", col="blue",
    main="Árvores", pch=20)    

plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab="Volume", col="blue",
    main="Árvores", pch=20, type="l")

plot(jitter(trees$Girth), trees$Volume, ylab="Circunferência", xlab="Volume", col="blue",
    main="Árvores", pch=20,)    

# tratando CO2 
plot(CO2$conc, CO2$uptake, pch=20, col=CO2$Treatment)
legend("bottomright", legend=c("nonchilled", "chilled"), cex=1, fill=c("black", "red"))

plot(trees)

'''{r}
boxplot(trees$Volume, main="Árvores", xlab="Volume")
boxplot(trees$Volume, main="Árvores", xlab="Volume", col="blue", horizontal=TRUE)
boxplot(trees$Volume, main="Árvores", xlab="Volume", col="blue", outline=F)
'''

'''{r}
#Comapara vários valores de boxplot
boxplot(trees)
'''

InsectSprays
spray = aggregate(. ~spray, data=InsectSprays, sum)
spray
barplot(spray$count, col=gray.colors(6), xlab="Spray", ylab="Total", 
        names.arg=spray$spray)
box()        

#gráfico de setor = gráfico de pizza

pie(spray$count, labels=spray$spray, main="Spray", col=(1:6))
pie(spray$count, labels=NA, main="Spray", col=c(1:6))
legend("bottomright", legend=spray$spray, cel=1, fill=c(1:6))






















